config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  #Compass members
  resources :members

 #Administrate dashboard
  namespace :admin do
    resources :contacts
    resources :dogs
    resources :members
    
    root to: "contacts#index"
  end

  resources :contacts


  #Adoption Pg
  get 'adoption' => 'dogs#adoption'

  #Adoptable dogs on Michigan Pg
  get 'michigan' => 'dogs#michigan'
  post 'michigan' => 'dogs#michigan'

  #Adoptable dogs on Michigan Pg
  get 'texas' => 'dogs#texas'
  post 'texas' => 'dogs#texas'

  #Adoptable dogs on Michigan Pg
  get 'foster' => 'dogs#foster'
  post 'foster' => 'dogs#foster'

  #Pending Adoption dogs 
  get 'pending' => 'dogs#pending'
  post 'pending' => 'dogs#pending'

  #Happy Tails dogs 
  get 'homed' => 'dogs#homed'
  post 'homed' => 'dogs#homed'

  resources :dogs

  get 'welcome/about'
  post 'welcome/about'

  get 'welcome/journey'

  get 'welcome/events'
  post 'welcome/events'

  get 'welcome/help'

  root to: 'welcome#index'


end

app/models/member.rb
class Member < ActiveRecord::Base
  
  #Validates first_name, last_name, email, capitalization
  include FormValidation

  before_validation :address_two_has_a_value
  
  validates :address_one, presence: true
  validates :address_two, presence: true, if: :address_two_has_a_value, allow_blank: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zipcode, numericality: { only_integer: true }, presence: true
  VALID_PHONE_REGEX = /\A\d{3}-\d{3}-\d{4}\z/
  validates :ph_primary, format: { with: VALID_PHONE_REGEX }, presence: true
  validates :ph_secondary, format: { with: VALID_PHONE_REGEX }, allow_blank: true
            
  private 
  #Capitalize only if data entered in address_two 
  def address_two_has_a_value
    self.address_two = address_two.split(' ').map {|a| a.capitalize }.join(' ')
  end

  attr_accessor :state_choice

  STATE_CHOICE = ['Texas', 'Michigan']
end

app/controllers/admin/members_controller.rb
module Admin
  class MembersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Member.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Member.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def index
  	@member = Member.all
  end

  def show
  end

  def new
  	@member = Member.new
  end

  def edit
  	@member = Member.find(params[:id])
  end

  def create
  	@member = Member.new(member_params)
    if @member.save
      flash[:notice] = "Member was saved successfully."
      redirect_to @member
    else
      flash[:error] = "Error: #{@member.errors.full_messages}."
      render :new 
    end
  end

  def update
    @member = Member.find(params[:id])  
    if @member.update_attributes(member_params)
       flash[:notice] = "Update successful."
       redirect_to @member
    else
      flash[:error] = "Error saving input. Please try again."
      render :edit
    end
  end

  def destroy
  	@member = Member.find(member_params[:id])
  	if @member.destroy
      flash[:notice] = "Member has been removed."
      redirect_to @member
    else
      flash[:error] = "Error: #{@member.errors.full_messages}."
    end
  end 

  private
  def member_params
  	 params.require(:member).permit(:first_name, :last_name, :address_one, :address_two, 
  	  	:city, :state, :zipcode, :ph_primary, :ph_secondary, :email)
  end

end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
    <div class="col-md-6 col-md-offset-3">
      <h1 class="form-heading">Add A New Member</h1>
        <div class="form-inputs">

          <%= simple_form_for @member, validate: true do |f| %>

            <div class="errors">
              <% if @member.errors.any? %>
                <h2>There are <%= pluralize(@member.errors.count, "error") %></h2>
                  <ul>
                    <% @member.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                    <% end %>
                  </ul>
              <% end %>
            </div>
            <div class="panel-body">
              <%= f.input :first_name, autofocus: true %>
              <%= f.input :last_name %>
              <%= f.input :address_one %>
              <%= f.input :address_two, placeholder: "Apt/Unit/Suite" %>
              <%= f.input :city %>
              <%= f.input :state, as: :radio_buttons, collection: Member::STATE_CHOICE, label: 'State' %>
              <%= f.input :zipcode %>
              <%= f.input :ph_primary, placeholder: "format xxx-xxx-xxxx" %>
              <%= f.input :ph_secondary, placeholder: "format xxx-xxx-xxxx" %>
              <%= f.input :email %>
            <%= f.submit "Submit", class: 'btn btn-success center-block' %>
          <% end %>
        </div>
      </div><!-- /.form-inputs -->
    </div><!-- /.col-md-6 col-md-offset-3 -->
  

app/views/members/edit.html.erb
<div class="container-fluid">
  <div class="row">
	<%= render 'members/form' %>
  </div>	
</div>

app/views/members/index.html.erb
<h1>Members#index</h1>
<p>Find me in app/views/members/index.html.erb</p>

app/views/members/new.html.erb
<div class="container-fluid">
  <div class="row">
  <%= render 'members/form' %>
  </div>  
</div>

app/views/members/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="heading member">New member has been added.</h1>
    </div>
  </div> 

  <div class="row confirm">
    <div class="col-md-6">
      <%= link_to 'Back', new_member_path, class: 'btn btn-primary pull-right' %> 
    </div>
    <div class="col-md-6">
      <%= link_to 'Edit', edit_member_path, class: 'btn btn-success pull-left' %> 
    </div>
  </div><!-- /.row -->  
</div><!-- /.container-fluid -->